spring:
  application:
    name: Safari
  main:
    banner-mode: off
    log-startup-info: true
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/safari
    password: safari
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always